### PR TITLE
something

### PR DESCRIPTION
**Pull request by YikaJ**
1. use self instead of `bind(this)`
2. get rid of ugly `switch` syntax, separate handle function from switch.
3. hope project more modularize.
4. jslint

tests passed

### CODE REVIEW

**Comment by adleroliveira** [comment]
I'm not convinced about the aliasing of the this. There is literature on why is better to use bind() when possible, instead of alias.

**Comment by tuhoojabotti** [comment]
@adleroliveira Do you happen to have any link to such literature? I prefer to use ES2015 arrow function fancyness. ;)

**Comment by YikaJ** [comment]
`bind()` will cost more memory beacause of closure, isn't it?
in the past, we use this way to bind function.

```
function bind(fn, context){
  return function(){
    return fn.apply(context, argument);
  }
}
```

I not sure how native `.bind(context)` works ~?

And, could I get the link to that literature, i hope to learn more about it :)

**Comment by tuhoojabotti** [comment]
@YikaJ Wouldn't using a self variable also create a closure? Also just like in your example, the name self doesn't really describe the variable, context is a lot better name for it in my opinion. I love the new arrow functions with Node, because they don't have a this, so they resolve it to the outer scope automatically.

I think the native bind is more or less the same, because most standard library functions are nowadays implemented in JavaScript instead of native code.

**Comment by YikaJ** [comment]
@tuhoojabotti 
I usually saw variable name as `context`, `self`, `_this` in other project, I don't think is the most important reason that not use a variable.

arrow function is cool, I like it too! But I think arrow function in CoffeeScript is better.

```coffeescript
notBindFunc = ()->
    // not bind

bindFunc = ()=>
    // bind
```

**Comment by tuhoojabotti** [comment]
@YikaJ I agree. I prefer to use plain JavaScript and function keyword if I need binding, arrow function is useful for small and simple callbacks, but I wouldn't use it with classes for example. I like how terse CoffeeScript can be, but it also requires you to know a lot more about the semantics of the language.

I think in this use case the arrow function would be the best choice, but of course that would require a recent Node version or a build process for transpilation.

**Comment by adleroliveira** [comment]
Usualy I fallow some best practices from this document: https://github.com/rwaldron/idiomatic.js

Have a look on the section **Faces of this**

Basicaly what it says is:

*"Beyond the generally well known use cases of call and apply, always prefer .bind( this ) or a functional equivalent, for creating BoundFunction definitions for later invocation. Only resort to aliasing when no preferable option is available"*

**Comment by tuhoojabotti** [comment]
@adleroliveira Naturally you are allowed to choose the style of your own code, but I find this comment weird in that document: "This [aliasing] is extremely bug prone and should be avoided whenever possible." I think both aliasing and binding are both bug prone, which is why a style guide is necessary. If you use one or the other, you have to remember to do it.

I'm not disagreeing with the use of bind or suggest using aliasing. I was just curious because I had not seen many style guides preferring bind. I think you should use the one you're more comfortable with. 

The only thing I do suggest is giving ES2015 arrow functions some thought, because they eliminate the need for both aliasing and binding. Then of course you'd have to think about compatibility or transpilation, in libraries it's more important than in applications because with an application you can choose the version of Node you use to run it.

**Pull request merged**
