### PR TITLE
this->self

### PR DESCRIPTION
**Pull request by ramikhalaf**
self is set to this on initialization but wasnt used for function assignments/declarations.
Switched to keep consistency. 
All tests passed!

### CODE REVIEW

**Comment by adleroliveira** [comment]
Your last pull request already have this.

**Comment by ramikhalaf** [comment]
Hey @adleroliveira!
I did not include this commit in the other pull request that was merged(it was a completely separate branch)

**Comment by adleroliveira** [comment]
Oh sorry, you are right. I can reopen it, but now it have conflicts with the current.
I can resolve the conflicts myself and merge or if you would be so kind to open another pull request with the changes this->self I can merge it.

**Comment by ramikhalaf** [comment]
@adleroliveira fixed and opened a new PR!

**Pull request closed without merging**
